// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
)

const ensureTeacher = `-- name: EnsureTeacher :one
INSERT INTO users(id, email, display_name, password_hash, role, created_at)
VALUES ('user:shared-teacher', 'shared-teacher@ai-tutor.invalid', 'Учитель', '!', 'admin', $1)
ON CONFLICT (id) DO UPDATE SET role = 'admin'
RETURNING id, email, display_name, role, created_at
`

type EnsureTeacherRow struct {
	ID          string
	Email       string
	DisplayName *string
	Role        string
	CreatedAt   int64
}

func (q *Queries) EnsureTeacher(ctx context.Context, createdAt int64) (EnsureTeacherRow, error) {
	row := q.db.QueryRow(ctx, ensureTeacher, createdAt)
	var i EnsureTeacherRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthContextByAccessToken = `-- name: GetAuthContextByAccessToken :one
SELECT s.id AS session_id, s.user_id, s.expires_at AS session_expires_at, s.revoked_at,
       t.expires_at AS token_expires_at, u.id AS account_id, u.email, u.display_name, u.role, u.created_at
FROM access_tokens AS t
JOIN auth_sessions AS s ON s.id = t.session_id
JOIN users AS u ON u.id = s.user_id
WHERE t.token_hash = $1
`

type GetAuthContextByAccessTokenRow struct {
	SessionID        string
	UserID           string
	SessionExpiresAt int64
	RevokedAt        *int64
	TokenExpiresAt   int64
	AccountID        string
	Email            string
	DisplayName      *string
	Role             string
	CreatedAt        int64
}

func (q *Queries) GetAuthContextByAccessToken(ctx context.Context, tokenHash []byte) (GetAuthContextByAccessTokenRow, error) {
	row := q.db.QueryRow(ctx, getAuthContextByAccessToken, tokenHash)
	var i GetAuthContextByAccessTokenRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.SessionExpiresAt,
		&i.RevokedAt,
		&i.TokenExpiresAt,
		&i.AccountID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenUsedAt = `-- name: GetRefreshTokenUsedAt :one
SELECT used_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenUsedAt(ctx context.Context, tokenHash []byte) (*int64, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenUsedAt, tokenHash)
	var used_at *int64
	err := row.Scan(&used_at)
	return used_at, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, email, display_name, role, created_at, password_hash
FROM users WHERE email = $1
`

type GetUserForLoginRow struct {
	ID           string
	Email        string
	DisplayName  *string
	Role         string
	CreatedAt    int64
	PasswordHash string
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const insertAccessToken = `-- name: InsertAccessToken :exec
INSERT INTO access_tokens(token_hash, session_id, expires_at) VALUES ($1, $2, $3)
`

type InsertAccessTokenParams struct {
	TokenHash []byte
	SessionID string
	ExpiresAt int64
}

func (q *Queries) InsertAccessToken(ctx context.Context, arg InsertAccessTokenParams) error {
	_, err := q.db.Exec(ctx, insertAccessToken, arg.TokenHash, arg.SessionID, arg.ExpiresAt)
	return err
}

const insertAuthSession = `-- name: InsertAuthSession :exec
INSERT INTO auth_sessions(id, user_id, expires_at) VALUES ($1, $2, $3)
`

type InsertAuthSessionParams struct {
	ID        string
	UserID    string
	ExpiresAt int64
}

func (q *Queries) InsertAuthSession(ctx context.Context, arg InsertAuthSessionParams) error {
	_, err := q.db.Exec(ctx, insertAuthSession, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens(token_hash, session_id) VALUES ($1, $2)
`

type InsertRefreshTokenParams struct {
	TokenHash []byte
	SessionID string
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken, arg.TokenHash, arg.SessionID)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users(id, email, display_name, password_hash, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertUserParams struct {
	ID           string
	Email        string
	DisplayName  *string
	PasswordHash string
	CreatedAt    int64
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const lockRefreshState = `-- name: LockRefreshState :one
SELECT s.id, s.expires_at, s.revoked_at, t.used_at
FROM refresh_tokens AS t
JOIN auth_sessions AS s ON s.id = t.session_id
WHERE t.token_hash = $1
FOR UPDATE OF s
`

type LockRefreshStateRow struct {
	ID        string
	ExpiresAt int64
	RevokedAt *int64
	UsedAt    *int64
}

func (q *Queries) LockRefreshState(ctx context.Context, tokenHash []byte) (LockRefreshStateRow, error) {
	row := q.db.QueryRow(ctx, lockRefreshState, tokenHash)
	var i LockRefreshStateRow
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UsedAt,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_tokens SET used_at = $2 WHERE token_hash = $1
`

type MarkRefreshTokenUsedParams struct {
	TokenHash []byte
	UsedAt    *int64
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.TokenHash, arg.UsedAt)
	return err
}

const revokeAuthSession = `-- name: RevokeAuthSession :exec
UPDATE auth_sessions SET revoked_at = COALESCE(revoked_at, $2) WHERE id = $1
`

type RevokeAuthSessionParams struct {
	ID        string
	RevokedAt *int64
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) error {
	_, err := q.db.Exec(ctx, revokeAuthSession, arg.ID, arg.RevokedAt)
	return err
}

const revokeSessionByRefreshToken = `-- name: RevokeSessionByRefreshToken :exec
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, $2)
WHERE id = (SELECT session_id FROM refresh_tokens WHERE token_hash = $1)
`

type RevokeSessionByRefreshTokenParams struct {
	TokenHash []byte
	RevokedAt *int64
}

func (q *Queries) RevokeSessionByRefreshToken(ctx context.Context, arg RevokeSessionByRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeSessionByRefreshToken, arg.TokenHash, arg.RevokedAt)
	return err
}
