// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competency.sql

package db

import (
	"context"
)

const countExistingOutcomes = `-- name: CountExistingOutcomes :one
SELECT count(*)::integer FROM outcomes WHERE id = ANY($1::text[])
`

func (q *Queries) CountExistingOutcomes(ctx context.Context, dollar_1 []string) (int32, error) {
	row := q.db.QueryRow(ctx, countExistingOutcomes, dollar_1)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteCompetencies = `-- name: DeleteCompetencies :exec
DELETE FROM competencies
`

func (q *Queries) DeleteCompetencies(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteCompetencies)
	return err
}

const deleteCompetencyMapImports = `-- name: DeleteCompetencyMapImports :exec
DELETE FROM competency_map_imports
`

func (q *Queries) DeleteCompetencyMapImports(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteCompetencyMapImports)
	return err
}

const deleteCompetencyMapSourceRows = `-- name: DeleteCompetencyMapSourceRows :exec
DELETE FROM competency_map_source_rows
`

func (q *Queries) DeleteCompetencyMapSourceRows(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteCompetencyMapSourceRows)
	return err
}

const deleteMaterialLinksByName = `-- name: DeleteMaterialLinksByName :exec
DELETE FROM material_chunk_outcomes
WHERE chunk_id IN (SELECT id FROM material_chunks WHERE material_name = $1)
`

func (q *Queries) DeleteMaterialLinksByName(ctx context.Context, materialName string) error {
	_, err := q.db.Exec(ctx, deleteMaterialLinksByName, materialName)
	return err
}

const getGeneratedTaskByKey = `-- name: GetGeneratedTaskByKey :one
SELECT task.id, task.outcome_id, task.question, task.options, task.voice_instruction,
       task.reference_answer, task.criteria, task.origin
FROM generation_runs AS run
JOIN tasks AS task ON task.generation_run_id = run.id
WHERE run.outcome_id = $1 AND run.request_key = $2
`

type GetGeneratedTaskByKeyParams struct {
	OutcomeID  string
	RequestKey string
}

type GetGeneratedTaskByKeyRow struct {
	ID               string
	OutcomeID        string
	Question         string
	Options          []byte
	VoiceInstruction *string
	ReferenceAnswer  *string
	Criteria         *string
	Origin           string
}

func (q *Queries) GetGeneratedTaskByKey(ctx context.Context, arg GetGeneratedTaskByKeyParams) (GetGeneratedTaskByKeyRow, error) {
	row := q.db.QueryRow(ctx, getGeneratedTaskByKey, arg.OutcomeID, arg.RequestKey)
	var i GetGeneratedTaskByKeyRow
	err := row.Scan(
		&i.ID,
		&i.OutcomeID,
		&i.Question,
		&i.Options,
		&i.VoiceInstruction,
		&i.ReferenceAnswer,
		&i.Criteria,
		&i.Origin,
	)
	return i, err
}

const getOutcomeForGeneration = `-- name: GetOutcomeForGeneration :one
SELECT state.revision, outcome.id, outcome.name, outcome.include_in_test, taxonomy.code AS taxonomy_code,
       ald.code AS ald_level_code, outcome.importance, outcome.educational_content,
       constituent.name AS constituent_name, topic.code AS topic_level_code,
       competency.name AS competency_name,
       COALESCE(curriculum_profile.curriculum_sections, '[]')::text AS curriculum_sections
FROM outcomes AS outcome
JOIN competency_map_state AS state ON state.singleton = true
JOIN constituents AS constituent ON constituent.id = outcome.constituent_id
JOIN constituent_curriculum_profiles AS curriculum_profile ON curriculum_profile.constituent_id = constituent.id
JOIN competencies AS competency ON competency.id = constituent.competency_id
LEFT JOIN taxonomies AS taxonomy ON taxonomy.id = outcome.taxonomy_id
LEFT JOIN ald_levels AS ald ON ald.id = outcome.ald_level_id
LEFT JOIN topic_levels AS topic ON topic.id = constituent.topic_level_id
WHERE outcome.id = $1
`

type GetOutcomeForGenerationRow struct {
	Revision           int64
	ID                 string
	Name               string
	IncludeInTest      *bool
	TaxonomyCode       *string
	AldLevelCode       *string
	Importance         *int16
	EducationalContent *string
	ConstituentName    string
	TopicLevelCode     *string
	CompetencyName     string
	CurriculumSections string
}

func (q *Queries) GetOutcomeForGeneration(ctx context.Context, id string) (GetOutcomeForGenerationRow, error) {
	row := q.db.QueryRow(ctx, getOutcomeForGeneration, id)
	var i GetOutcomeForGenerationRow
	err := row.Scan(
		&i.Revision,
		&i.ID,
		&i.Name,
		&i.IncludeInTest,
		&i.TaxonomyCode,
		&i.AldLevelCode,
		&i.Importance,
		&i.EducationalContent,
		&i.ConstituentName,
		&i.TopicLevelCode,
		&i.CompetencyName,
		&i.CurriculumSections,
	)
	return i, err
}

const getTaskProfile = `-- name: GetTaskProfile :one
SELECT
    task.id AS task_id, task.question, task.options, task.voice_instruction,
    task.reference_answer, task.criteria, task.origin, task.created_at,
    outcome.id AS outcome_id, outcome.name AS outcome_name,
    outcome.include_in_test, taxonomy.code AS taxonomy_code,
    ald.code AS ald_level_code, outcome.importance, outcome.educational_content,
    constituent.id AS constituent_id, constituent.name AS constituent_name,
    topic.code AS topic_level_code,
    competency.id AS competency_id, competency.name AS competency_name,
    COALESCE(curriculum_profile.curriculum_sections, '[]')::text AS curriculum_sections
FROM tasks AS task
JOIN outcomes AS outcome ON outcome.id = task.outcome_id
JOIN constituents AS constituent ON constituent.id = outcome.constituent_id
JOIN constituent_curriculum_profiles AS curriculum_profile ON curriculum_profile.constituent_id = constituent.id
JOIN competencies AS competency ON competency.id = constituent.competency_id
LEFT JOIN taxonomies AS taxonomy ON taxonomy.id = outcome.taxonomy_id
LEFT JOIN ald_levels AS ald ON ald.id = outcome.ald_level_id
LEFT JOIN topic_levels AS topic ON topic.id = constituent.topic_level_id
WHERE task.id = $1
`

type GetTaskProfileRow struct {
	TaskID             string
	Question           string
	Options            []byte
	VoiceInstruction   *string
	ReferenceAnswer    *string
	Criteria           *string
	Origin             string
	CreatedAt          int64
	OutcomeID          string
	OutcomeName        string
	IncludeInTest      *bool
	TaxonomyCode       *string
	AldLevelCode       *string
	Importance         *int16
	EducationalContent *string
	ConstituentID      string
	ConstituentName    string
	TopicLevelCode     *string
	CompetencyID       string
	CompetencyName     string
	CurriculumSections string
}

func (q *Queries) GetTaskProfile(ctx context.Context, id string) (GetTaskProfileRow, error) {
	row := q.db.QueryRow(ctx, getTaskProfile, id)
	var i GetTaskProfileRow
	err := row.Scan(
		&i.TaskID,
		&i.Question,
		&i.Options,
		&i.VoiceInstruction,
		&i.ReferenceAnswer,
		&i.Criteria,
		&i.Origin,
		&i.CreatedAt,
		&i.OutcomeID,
		&i.OutcomeName,
		&i.IncludeInTest,
		&i.TaxonomyCode,
		&i.AldLevelCode,
		&i.Importance,
		&i.EducationalContent,
		&i.ConstituentID,
		&i.ConstituentName,
		&i.TopicLevelCode,
		&i.CompetencyID,
		&i.CompetencyName,
		&i.CurriculumSections,
	)
	return i, err
}

const insertCompetency = `-- name: InsertCompetency :exec
INSERT INTO competencies(id, name, revision) VALUES ($1, $2, $3)
`

type InsertCompetencyParams struct {
	ID       string
	Name     string
	Revision int64
}

func (q *Queries) InsertCompetency(ctx context.Context, arg InsertCompetencyParams) error {
	_, err := q.db.Exec(ctx, insertCompetency, arg.ID, arg.Name, arg.Revision)
	return err
}

const insertCompetencyMapImport = `-- name: InsertCompetencyMapImport :exec
INSERT INTO competency_map_imports(
    revision, imported_at, imported_by, competency_count, constituent_count,
    outcome_count, task_count, source_format, source_headers, unparsed_task_cell_count
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertCompetencyMapImportParams struct {
	Revision              int64
	ImportedAt            int64
	ImportedBy            string
	CompetencyCount       int32
	ConstituentCount      int32
	OutcomeCount          int32
	TaskCount             int32
	SourceFormat          string
	SourceHeaders         []byte
	UnparsedTaskCellCount int32
}

func (q *Queries) InsertCompetencyMapImport(ctx context.Context, arg InsertCompetencyMapImportParams) error {
	_, err := q.db.Exec(ctx, insertCompetencyMapImport,
		arg.Revision,
		arg.ImportedAt,
		arg.ImportedBy,
		arg.CompetencyCount,
		arg.ConstituentCount,
		arg.OutcomeCount,
		arg.TaskCount,
		arg.SourceFormat,
		arg.SourceHeaders,
		arg.UnparsedTaskCellCount,
	)
	return err
}

const insertCompetencyMapSourceRow = `-- name: InsertCompetencyMapSourceRow :exec
INSERT INTO competency_map_source_rows(revision, row_index, source_line, cells)
VALUES ($1, $2, $3, $4)
`

type InsertCompetencyMapSourceRowParams struct {
	Revision   int64
	RowIndex   int32
	SourceLine int32
	Cells      []byte
}

func (q *Queries) InsertCompetencyMapSourceRow(ctx context.Context, arg InsertCompetencyMapSourceRowParams) error {
	_, err := q.db.Exec(ctx, insertCompetencyMapSourceRow,
		arg.Revision,
		arg.RowIndex,
		arg.SourceLine,
		arg.Cells,
	)
	return err
}

const insertConstituent = `-- name: InsertConstituent :exec
INSERT INTO constituents(id, competency_id, name, topic_level_id)
VALUES ($1, $2, $3, NULLIF($4::text, ''))
`

type InsertConstituentParams struct {
	ID           string
	CompetencyID string
	Name         string
	TopicLevelID string
}

func (q *Queries) InsertConstituent(ctx context.Context, arg InsertConstituentParams) error {
	_, err := q.db.Exec(ctx, insertConstituent,
		arg.ID,
		arg.CompetencyID,
		arg.Name,
		arg.TopicLevelID,
	)
	return err
}

const insertConstituentSection = `-- name: InsertConstituentSection :exec
INSERT INTO constituent_sections(id, revision, constituent_id, section_id)
VALUES ($1, $2, $3, $4)
`

type InsertConstituentSectionParams struct {
	ID            string
	Revision      int64
	ConstituentID string
	SectionID     string
}

func (q *Queries) InsertConstituentSection(ctx context.Context, arg InsertConstituentSectionParams) error {
	_, err := q.db.Exec(ctx, insertConstituentSection,
		arg.ID,
		arg.Revision,
		arg.ConstituentID,
		arg.SectionID,
	)
	return err
}

const insertConstituentSectionCompetency = `-- name: InsertConstituentSectionCompetency :exec
INSERT INTO constituent_section_competencies(revision, constituent_section_id, curriculum_competency_id)
VALUES ($1, $2, $3)
`

type InsertConstituentSectionCompetencyParams struct {
	Revision               int64
	ConstituentSectionID   string
	CurriculumCompetencyID string
}

func (q *Queries) InsertConstituentSectionCompetency(ctx context.Context, arg InsertConstituentSectionCompetencyParams) error {
	_, err := q.db.Exec(ctx, insertConstituentSectionCompetency, arg.Revision, arg.ConstituentSectionID, arg.CurriculumCompetencyID)
	return err
}

const insertCurriculumCompetency = `-- name: InsertCurriculumCompetency :exec
INSERT INTO curriculum_competencies(id, revision, code) VALUES ($1, $2, $3)
`

type InsertCurriculumCompetencyParams struct {
	ID       string
	Revision int64
	Code     string
}

func (q *Queries) InsertCurriculumCompetency(ctx context.Context, arg InsertCurriculumCompetencyParams) error {
	_, err := q.db.Exec(ctx, insertCurriculumCompetency, arg.ID, arg.Revision, arg.Code)
	return err
}

const insertCurriculumSection = `-- name: InsertCurriculumSection :exec
INSERT INTO curriculum_sections(id, revision, code, title) VALUES ($1, $2, $3, $4)
`

type InsertCurriculumSectionParams struct {
	ID       string
	Revision int64
	Code     string
	Title    string
}

func (q *Queries) InsertCurriculumSection(ctx context.Context, arg InsertCurriculumSectionParams) error {
	_, err := q.db.Exec(ctx, insertCurriculumSection,
		arg.ID,
		arg.Revision,
		arg.Code,
		arg.Title,
	)
	return err
}

const insertGeneratedTask = `-- name: InsertGeneratedTask :exec
INSERT INTO tasks(id, outcome_id, question, options, voice_instruction, reference_answer, criteria,
                  origin, generation_run_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'ai_generated', $8, $9)
`

type InsertGeneratedTaskParams struct {
	ID               string
	OutcomeID        string
	Question         string
	Options          []byte
	VoiceInstruction *string
	ReferenceAnswer  *string
	Criteria         *string
	GenerationRunID  *string
	CreatedAt        int64
}

func (q *Queries) InsertGeneratedTask(ctx context.Context, arg InsertGeneratedTaskParams) error {
	_, err := q.db.Exec(ctx, insertGeneratedTask,
		arg.ID,
		arg.OutcomeID,
		arg.Question,
		arg.Options,
		arg.VoiceInstruction,
		arg.ReferenceAnswer,
		arg.Criteria,
		arg.GenerationRunID,
		arg.CreatedAt,
	)
	return err
}

const insertGenerationRun = `-- name: InsertGenerationRun :execrows
INSERT INTO generation_runs(id, outcome_id, map_revision, model, prompt_version, request_key, requested_profile, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (outcome_id, request_key) DO NOTHING
`

type InsertGenerationRunParams struct {
	ID               string
	OutcomeID        string
	MapRevision      int64
	Model            string
	PromptVersion    string
	RequestKey       string
	RequestedProfile []byte
	CreatedAt        int64
}

func (q *Queries) InsertGenerationRun(ctx context.Context, arg InsertGenerationRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertGenerationRun,
		arg.ID,
		arg.OutcomeID,
		arg.MapRevision,
		arg.Model,
		arg.PromptVersion,
		arg.RequestKey,
		arg.RequestedProfile,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertGenerationRunChunk = `-- name: InsertGenerationRunChunk :exec
INSERT INTO generation_run_chunks(generation_run_id, chunk_id) VALUES ($1, $2)
`

type InsertGenerationRunChunkParams struct {
	GenerationRunID string
	ChunkID         string
}

func (q *Queries) InsertGenerationRunChunk(ctx context.Context, arg InsertGenerationRunChunkParams) error {
	_, err := q.db.Exec(ctx, insertGenerationRunChunk, arg.GenerationRunID, arg.ChunkID)
	return err
}

const insertGenerationRunExample = `-- name: InsertGenerationRunExample :exec
INSERT INTO generation_run_examples(generation_run_id, task_id) VALUES ($1, $2)
`

type InsertGenerationRunExampleParams struct {
	GenerationRunID string
	TaskID          string
}

func (q *Queries) InsertGenerationRunExample(ctx context.Context, arg InsertGenerationRunExampleParams) error {
	_, err := q.db.Exec(ctx, insertGenerationRunExample, arg.GenerationRunID, arg.TaskID)
	return err
}

const insertMaterialChunk = `-- name: InsertMaterialChunk :exec
INSERT INTO material_chunks(id, material_name, ordinal, content, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertMaterialChunkParams struct {
	ID           string
	MaterialName string
	Ordinal      int32
	Content      string
	CreatedAt    int64
}

func (q *Queries) InsertMaterialChunk(ctx context.Context, arg InsertMaterialChunkParams) error {
	_, err := q.db.Exec(ctx, insertMaterialChunk,
		arg.ID,
		arg.MaterialName,
		arg.Ordinal,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const insertOutcome = `-- name: InsertOutcome :exec
INSERT INTO outcomes(
    id, constituent_id, name, include_in_test, taxonomy_id,
    ald_level_id, importance, educational_content
) VALUES (
    $1, $2, $3, $4,
    (SELECT id FROM taxonomies WHERE code = NULLIF($5::text, '')),
    (SELECT id FROM ald_levels WHERE code = NULLIF($6::text, '')),
    NULLIF($7::smallint, 0), NULLIF($8::text, '')
)
`

type InsertOutcomeParams struct {
	ID                 string
	ConstituentID      string
	Name               string
	IncludeInTest      *bool
	TaxonomyCode       string
	AldLevelCode       string
	Importance         int16
	EducationalContent string
}

func (q *Queries) InsertOutcome(ctx context.Context, arg InsertOutcomeParams) error {
	_, err := q.db.Exec(ctx, insertOutcome,
		arg.ID,
		arg.ConstituentID,
		arg.Name,
		arg.IncludeInTest,
		arg.TaxonomyCode,
		arg.AldLevelCode,
		arg.Importance,
		arg.EducationalContent,
	)
	return err
}

const insertOutcomeSourceRow = `-- name: InsertOutcomeSourceRow :exec
INSERT INTO outcome_source_rows(outcome_id, source_revision, source_row_index)
VALUES ($1, $2, $3)
`

type InsertOutcomeSourceRowParams struct {
	OutcomeID      string
	SourceRevision int64
	SourceRowIndex int32
}

func (q *Queries) InsertOutcomeSourceRow(ctx context.Context, arg InsertOutcomeSourceRowParams) error {
	_, err := q.db.Exec(ctx, insertOutcomeSourceRow, arg.OutcomeID, arg.SourceRevision, arg.SourceRowIndex)
	return err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO tasks(
    id, outcome_id, question, criteria, source_row, source_column, options,
    voice_instruction, reference_answer, origin, source_revision,
    source_row_index, source_column_index, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, 'authored',
    NULLIF($10::bigint, 0),
    NULLIF($11::integer, 0),
    NULLIF($12::integer, 0),
    $13::bigint
)
`

type InsertTaskParams struct {
	ID                string
	OutcomeID         string
	Question          string
	Criteria          *string
	SourceRow         *int32
	SourceColumn      *string
	Options           []byte
	VoiceInstruction  *string
	ReferenceAnswer   *string
	SourceRevision    int64
	SourceRowIndex    int32
	SourceColumnIndex int32
	CreatedAt         int64
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.Exec(ctx, insertTask,
		arg.ID,
		arg.OutcomeID,
		arg.Question,
		arg.Criteria,
		arg.SourceRow,
		arg.SourceColumn,
		arg.Options,
		arg.VoiceInstruction,
		arg.ReferenceAnswer,
		arg.SourceRevision,
		arg.SourceRowIndex,
		arg.SourceColumnIndex,
		arg.CreatedAt,
	)
	return err
}

const linkMaterialChunkToOutcome = `-- name: LinkMaterialChunkToOutcome :exec
INSERT INTO material_chunk_outcomes(chunk_id, outcome_id) VALUES ($1, $2)
`

type LinkMaterialChunkToOutcomeParams struct {
	ChunkID   string
	OutcomeID string
}

func (q *Queries) LinkMaterialChunkToOutcome(ctx context.Context, arg LinkMaterialChunkToOutcomeParams) error {
	_, err := q.db.Exec(ctx, linkMaterialChunkToOutcome, arg.ChunkID, arg.OutcomeID)
	return err
}

const listGenerationExamples = `-- name: ListGenerationExamples :many
SELECT task.id, task.question, task.options, task.voice_instruction, task.reference_answer, task.criteria
FROM tasks AS task
WHERE task.outcome_id = $1
ORDER BY CASE WHEN task.origin = 'authored' THEN 0 ELSE 1 END, task.created_at DESC, task.id
LIMIT $2
`

type ListGenerationExamplesParams struct {
	OutcomeID string
	Limit     int32
}

type ListGenerationExamplesRow struct {
	ID               string
	Question         string
	Options          []byte
	VoiceInstruction *string
	ReferenceAnswer  *string
	Criteria         *string
}

func (q *Queries) ListGenerationExamples(ctx context.Context, arg ListGenerationExamplesParams) ([]ListGenerationExamplesRow, error) {
	rows, err := q.db.Query(ctx, listGenerationExamples, arg.OutcomeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGenerationExamplesRow{}
	for rows.Next() {
		var i ListGenerationExamplesRow
		if err := rows.Scan(
			&i.ID,
			&i.Question,
			&i.Options,
			&i.VoiceInstruction,
			&i.ReferenceAnswer,
			&i.Criteria,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCompetencyMapRevision = `-- name: LockCompetencyMapRevision :one
SELECT revision FROM competency_map_state WHERE singleton = true FOR UPDATE
`

func (q *Queries) LockCompetencyMapRevision(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, lockCompetencyMapRevision)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const readCurrentCompetencyMap = `-- name: ReadCurrentCompetencyMap :many
SELECT state.revision, import.imported_at,
       competency.id AS competency_id, competency.name AS competency_name,
       constituent.id AS constituent_id, constituent.name AS constituent_name,
       topic.code AS topic_level_code,
       COALESCE(curriculum_profile.curriculum_sections, '[]')::text AS curriculum_sections,
       outcome.id AS outcome_id, outcome.name AS outcome_name,
       outcome.include_in_test, taxonomy.code AS taxonomy_code,
       ald.code AS ald_level_code, outcome.importance, outcome.educational_content,
       task.id AS task_id, task.question, task.options, task.voice_instruction, task.origin
FROM competency_map_state AS state
LEFT JOIN competency_map_imports AS import ON import.revision = state.revision
LEFT JOIN competencies AS competency ON competency.revision = state.revision
LEFT JOIN constituents AS constituent ON constituent.competency_id = competency.id
LEFT JOIN topic_levels AS topic ON topic.id = constituent.topic_level_id
LEFT JOIN constituent_curriculum_profiles AS curriculum_profile ON curriculum_profile.constituent_id = constituent.id
LEFT JOIN outcomes AS outcome ON outcome.constituent_id = constituent.id
LEFT JOIN taxonomies AS taxonomy ON taxonomy.id = outcome.taxonomy_id
LEFT JOIN ald_levels AS ald ON ald.id = outcome.ald_level_id
LEFT JOIN tasks AS task ON task.outcome_id = outcome.id
WHERE state.singleton = true
ORDER BY competency.name, competency.id, constituent.name, constituent.id,
         outcome.name, outcome.id, task.created_at, task.id
`

type ReadCurrentCompetencyMapRow struct {
	Revision           int64
	ImportedAt         *int64
	CompetencyID       *string
	CompetencyName     *string
	ConstituentID      *string
	ConstituentName    *string
	TopicLevelCode     *string
	CurriculumSections string
	OutcomeID          *string
	OutcomeName        *string
	IncludeInTest      *bool
	TaxonomyCode       *string
	AldLevelCode       *string
	Importance         *int16
	EducationalContent *string
	TaskID             *string
	Question           *string
	Options            []byte
	VoiceInstruction   *string
	Origin             *string
}

func (q *Queries) ReadCurrentCompetencyMap(ctx context.Context) ([]ReadCurrentCompetencyMapRow, error) {
	rows, err := q.db.Query(ctx, readCurrentCompetencyMap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadCurrentCompetencyMapRow{}
	for rows.Next() {
		var i ReadCurrentCompetencyMapRow
		if err := rows.Scan(
			&i.Revision,
			&i.ImportedAt,
			&i.CompetencyID,
			&i.CompetencyName,
			&i.ConstituentID,
			&i.ConstituentName,
			&i.TopicLevelCode,
			&i.CurriculumSections,
			&i.OutcomeID,
			&i.OutcomeName,
			&i.IncludeInTest,
			&i.TaxonomyCode,
			&i.AldLevelCode,
			&i.Importance,
			&i.EducationalContent,
			&i.TaskID,
			&i.Question,
			&i.Options,
			&i.VoiceInstruction,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMaterialChunks = `-- name: SearchMaterialChunks :many
SELECT chunk.id, chunk.material_name, chunk.ordinal, chunk.content,
       ts_rank_cd(chunk.search_vector, to_tsquery('russian', replace(plainto_tsquery('russian', $2)::text, ' & ', ' | '))) AS relevance
FROM material_chunks AS chunk
JOIN material_chunk_outcomes AS link ON link.chunk_id = chunk.id
WHERE link.outcome_id = $1
  AND chunk.search_vector @@ to_tsquery('russian', replace(plainto_tsquery('russian', $2)::text, ' & ', ' | '))
ORDER BY relevance DESC, chunk.id
LIMIT $3
`

type SearchMaterialChunksParams struct {
	OutcomeID      string
	PlaintoTsquery string
	Limit          int32
}

type SearchMaterialChunksRow struct {
	ID           string
	MaterialName string
	Ordinal      int32
	Content      string
	Relevance    float32
}

func (q *Queries) SearchMaterialChunks(ctx context.Context, arg SearchMaterialChunksParams) ([]SearchMaterialChunksRow, error) {
	rows, err := q.db.Query(ctx, searchMaterialChunks, arg.OutcomeID, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMaterialChunksRow{}
	for rows.Next() {
		var i SearchMaterialChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.MaterialName,
			&i.Ordinal,
			&i.Content,
			&i.Relevance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTaskProfiles = `-- name: SearchTaskProfiles :many
SELECT task.id, task.question, task.options, task.voice_instruction,
       task.origin, outcome.id AS outcome_id, outcome.name AS outcome_name,
       competency.name AS competency_name, constituent.name AS constituent_name,
       taxonomy.code AS taxonomy_code, ald.code AS ald_level_code,
       topic.code AS topic_level_code, outcome.importance, outcome.include_in_test
FROM tasks AS task
JOIN outcomes AS outcome ON outcome.id = task.outcome_id
JOIN constituents AS constituent ON constituent.id = outcome.constituent_id
JOIN competencies AS competency ON competency.id = constituent.competency_id
LEFT JOIN taxonomies AS taxonomy ON taxonomy.id = outcome.taxonomy_id
LEFT JOIN ald_levels AS ald ON ald.id = outcome.ald_level_id
LEFT JOIN topic_levels AS topic ON topic.id = constituent.topic_level_id
WHERE ($1::text = '' OR outcome.id = $1::text)
  AND ($2::text = '' OR competency.id = $2::text)
  AND ($3::text = '' OR constituent.id = $3::text)
  AND ($4::text = '' OR taxonomy.code = $4::text)
  AND ($5::text = '' OR ald.code = $5::text)
  AND ($6::text = '' OR topic.code = $6::text)
  AND ($7::smallint = 0 OR outcome.importance = $7::smallint)
  AND ($8::smallint = 0 OR outcome.importance >= $8::smallint)
  AND ($9::smallint = 0 OR outcome.importance <= $9::smallint)
  AND ($10::integer < 0 OR outcome.include_in_test = ($10::integer = 1))
  AND ($11::text = '' OR task.origin = $11::text)
  AND (($12::text = '' AND $13::text = '') OR EXISTS (
      SELECT 1 FROM constituent_sections AS link
      JOIN curriculum_sections AS section ON section.id = link.section_id
      LEFT JOIN constituent_section_competencies AS mapped ON mapped.constituent_section_id = link.id
      LEFT JOIN curriculum_competencies AS curriculum ON curriculum.id = mapped.curriculum_competency_id
      WHERE link.constituent_id = constituent.id
        AND ($12::text = '' OR section.code = $12::text)
        AND ($13::text = '' OR curriculum.code = $13::text)
  ))
ORDER BY task.created_at, task.id
LIMIT $14::integer
`

type SearchTaskProfilesParams struct {
	OutcomeID                string
	CompetencyID             string
	ConstituentID            string
	TaxonomyCode             string
	AldLevelCode             string
	TopicLevelCode           string
	Importance               int16
	ImportanceMin            int16
	ImportanceMax            int16
	IncludeInTest            int32
	Origin                   string
	SectionCode              string
	CurriculumCompetencyCode string
	TaskLimit                int32
}

type SearchTaskProfilesRow struct {
	ID               string
	Question         string
	Options          []byte
	VoiceInstruction *string
	Origin           string
	OutcomeID        string
	OutcomeName      string
	CompetencyName   string
	ConstituentName  string
	TaxonomyCode     *string
	AldLevelCode     *string
	TopicLevelCode   *string
	Importance       *int16
	IncludeInTest    *bool
}

func (q *Queries) SearchTaskProfiles(ctx context.Context, arg SearchTaskProfilesParams) ([]SearchTaskProfilesRow, error) {
	rows, err := q.db.Query(ctx, searchTaskProfiles,
		arg.OutcomeID,
		arg.CompetencyID,
		arg.ConstituentID,
		arg.TaxonomyCode,
		arg.AldLevelCode,
		arg.TopicLevelCode,
		arg.Importance,
		arg.ImportanceMin,
		arg.ImportanceMax,
		arg.IncludeInTest,
		arg.Origin,
		arg.SectionCode,
		arg.CurriculumCompetencyCode,
		arg.TaskLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTaskProfilesRow{}
	for rows.Next() {
		var i SearchTaskProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Question,
			&i.Options,
			&i.VoiceInstruction,
			&i.Origin,
			&i.OutcomeID,
			&i.OutcomeName,
			&i.CompetencyName,
			&i.ConstituentName,
			&i.TaxonomyCode,
			&i.AldLevelCode,
			&i.TopicLevelCode,
			&i.Importance,
			&i.IncludeInTest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompetencyMapRevision = `-- name: UpdateCompetencyMapRevision :exec
UPDATE competency_map_state SET revision = $1 WHERE singleton = true
`

func (q *Queries) UpdateCompetencyMapRevision(ctx context.Context, revision int64) error {
	_, err := q.db.Exec(ctx, updateCompetencyMapRevision, revision)
	return err
}
