// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diagnostic.sql

package db

import (
	"context"
)

const createDiagnosticSession = `-- name: CreateDiagnosticSession :execrows
INSERT INTO diagnostic_sessions(
    id, owner_id, variant_id, subject_id, subject_name_snapshot, map_revision, status,
    current_competency, current_task, start_request_key, start_request_digest, session_data
)
SELECT $1::text, $2::text, variant.id, variant.subject_id,
       variant.subject_name_snapshot, variant.map_revision, $3::text,
       $4::integer, $5::integer,
       $6::text, $7::text,
       $8::jsonb
FROM variants AS variant
WHERE variant.id = $9::text
  AND variant.user_id = $2::text
ON CONFLICT (owner_id, start_request_key) DO NOTHING
`

type CreateDiagnosticSessionParams struct {
	ID                 string
	OwnerID            string
	Status             string
	CurrentCompetency  int32
	CurrentTask        int32
	StartRequestKey    string
	StartRequestDigest string
	SessionData        []byte
	VariantID          string
}

func (q *Queries) CreateDiagnosticSession(ctx context.Context, arg CreateDiagnosticSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createDiagnosticSession,
		arg.ID,
		arg.OwnerID,
		arg.Status,
		arg.CurrentCompetency,
		arg.CurrentTask,
		arg.StartRequestKey,
		arg.StartRequestDigest,
		arg.SessionData,
		arg.VariantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findDiagnosticSessionByStart = `-- name: FindDiagnosticSessionByStart :one
SELECT session_data, start_request_digest
FROM diagnostic_sessions
WHERE owner_id = $1::text
  AND start_request_key = $2::text
`

type FindDiagnosticSessionByStartParams struct {
	OwnerID         string
	StartRequestKey string
}

type FindDiagnosticSessionByStartRow struct {
	SessionData        []byte
	StartRequestDigest string
}

func (q *Queries) FindDiagnosticSessionByStart(ctx context.Context, arg FindDiagnosticSessionByStartParams) (FindDiagnosticSessionByStartRow, error) {
	row := q.db.QueryRow(ctx, findDiagnosticSessionByStart, arg.OwnerID, arg.StartRequestKey)
	var i FindDiagnosticSessionByStartRow
	err := row.Scan(&i.SessionData, &i.StartRequestDigest)
	return i, err
}

const getDiagnosticSession = `-- name: GetDiagnosticSession :one
SELECT session_data
FROM diagnostic_sessions
WHERE owner_id = $1::text
  AND id = $2::text
`

type GetDiagnosticSessionParams struct {
	OwnerID string
	ID      string
}

func (q *Queries) GetDiagnosticSession(ctx context.Context, arg GetDiagnosticSessionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDiagnosticSession, arg.OwnerID, arg.ID)
	var session_data []byte
	err := row.Scan(&session_data)
	return session_data, err
}

const insertDiagnosticAnswer = `-- name: InsertDiagnosticAnswer :exec
INSERT INTO diagnostic_answers(session_id,answer_order,idempotency_key,request_digest,variant_task_id,answer_data,progress_data) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type InsertDiagnosticAnswerParams struct {
	SessionID      string
	AnswerOrder    int32
	IdempotencyKey string
	RequestDigest  string
	VariantTaskID  string
	AnswerData     []byte
	ProgressData   []byte
}

func (q *Queries) InsertDiagnosticAnswer(ctx context.Context, arg InsertDiagnosticAnswerParams) error {
	_, err := q.db.Exec(ctx, insertDiagnosticAnswer,
		arg.SessionID,
		arg.AnswerOrder,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.VariantTaskID,
		arg.AnswerData,
		arg.ProgressData,
	)
	return err
}

const latestCompletedDiagnostic = `-- name: LatestCompletedDiagnostic :one
SELECT session_data FROM diagnostic_sessions WHERE owner_id=$1 AND subject_id=$2 AND status='completed' ORDER BY completed_at DESC NULLS LAST,id DESC LIMIT 1
`

type LatestCompletedDiagnosticParams struct {
	OwnerID   string
	SubjectID string
}

func (q *Queries) LatestCompletedDiagnostic(ctx context.Context, arg LatestCompletedDiagnosticParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, latestCompletedDiagnostic, arg.OwnerID, arg.SubjectID)
	var session_data []byte
	err := row.Scan(&session_data)
	return session_data, err
}

const lockDiagnosticSession = `-- name: LockDiagnosticSession :one
SELECT session_data,COALESCE(lease_until>now(),false)::boolean AS leased FROM diagnostic_sessions WHERE owner_id=$1 AND id=$2 FOR UPDATE
`

type LockDiagnosticSessionParams struct {
	OwnerID string
	ID      string
}

type LockDiagnosticSessionRow struct {
	SessionData []byte
	Leased      bool
}

func (q *Queries) LockDiagnosticSession(ctx context.Context, arg LockDiagnosticSessionParams) (LockDiagnosticSessionRow, error) {
	row := q.db.QueryRow(ctx, lockDiagnosticSession, arg.OwnerID, arg.ID)
	var i LockDiagnosticSessionRow
	err := row.Scan(&i.SessionData, &i.Leased)
	return i, err
}

const readSubjectLearningState = `-- name: ReadSubjectLearningState :one
SELECT subject.id,subject.name,
 COALESCE((SELECT id FROM diagnostic_sessions d WHERE d.owner_id=$1::text AND d.subject_id=subject.id AND d.status='completed' ORDER BY d.completed_at DESC NULLS LAST,d.id DESC LIMIT 1),'')::text AS completed_id,
 COALESCE((SELECT id FROM diagnostic_sessions d WHERE d.owner_id=$1::text AND d.subject_id=subject.id AND d.status='active' ORDER BY d.created_at DESC,d.id DESC LIMIT 1),'')::text AS active_id
FROM subjects subject WHERE subject.id=$2::text
`

type ReadSubjectLearningStateParams struct {
	OwnerID   string
	SubjectID string
}

type ReadSubjectLearningStateRow struct {
	ID          string
	Name        string
	CompletedID string
	ActiveID    string
}

func (q *Queries) ReadSubjectLearningState(ctx context.Context, arg ReadSubjectLearningStateParams) (ReadSubjectLearningStateRow, error) {
	row := q.db.QueryRow(ctx, readSubjectLearningState, arg.OwnerID, arg.SubjectID)
	var i ReadSubjectLearningStateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CompletedID,
		&i.ActiveID,
	)
	return i, err
}

const saveDiagnosticSession = `-- name: SaveDiagnosticSession :exec
UPDATE diagnostic_sessions SET session_data=$2,status=$3,current_competency=$4,current_task=$5,
updated_at=now(),lease_until=CASE WHEN $6::boolean THEN now()+interval '5 minutes' ELSE NULL END,
completed_at=CASE WHEN $3='completed' THEN COALESCE(completed_at,now()) ELSE completed_at END WHERE id=$1
`

type SaveDiagnosticSessionParams struct {
	ID                string
	SessionData       []byte
	Status            string
	CurrentCompetency int32
	CurrentTask       int32
	Leased            bool
}

func (q *Queries) SaveDiagnosticSession(ctx context.Context, arg SaveDiagnosticSessionParams) error {
	_, err := q.db.Exec(ctx, saveDiagnosticSession,
		arg.ID,
		arg.SessionData,
		arg.Status,
		arg.CurrentCompetency,
		arg.CurrentTask,
		arg.Leased,
	)
	return err
}
