// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diagnostic.sql

package db

import (
	"context"
)

const createDiagnosticSession = `-- name: CreateDiagnosticSession :execrows
INSERT INTO diagnostic_sessions(
    id, owner_id, variant_id, subject_id, subject_name_snapshot, map_revision, status,
    current_competency, current_task, start_request_key, start_request_digest, session_data
)
SELECT $1::text, $2::text, variant.id, variant.subject_id,
       variant.subject_name_snapshot, variant.map_revision, $3::text,
       $4::integer, $5::integer,
       $6::text, $7::text,
       $8::jsonb
FROM variants AS variant
WHERE variant.id = $9::text
  AND variant.user_id = $2::text
ON CONFLICT (owner_id, start_request_key) DO NOTHING
`

type CreateDiagnosticSessionParams struct {
	ID                 string
	OwnerID            string
	Status             string
	CurrentCompetency  int32
	CurrentTask        int32
	StartRequestKey    string
	StartRequestDigest string
	SessionData        []byte
	VariantID          string
}

func (q *Queries) CreateDiagnosticSession(ctx context.Context, arg CreateDiagnosticSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createDiagnosticSession,
		arg.ID,
		arg.OwnerID,
		arg.Status,
		arg.CurrentCompetency,
		arg.CurrentTask,
		arg.StartRequestKey,
		arg.StartRequestDigest,
		arg.SessionData,
		arg.VariantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findDiagnosticSessionByStart = `-- name: FindDiagnosticSessionByStart :one
SELECT session_data, start_request_digest
FROM diagnostic_sessions
WHERE owner_id = $1::text
  AND start_request_key = $2::text
`

type FindDiagnosticSessionByStartParams struct {
	OwnerID         string
	StartRequestKey string
}

type FindDiagnosticSessionByStartRow struct {
	SessionData        []byte
	StartRequestDigest string
}

func (q *Queries) FindDiagnosticSessionByStart(ctx context.Context, arg FindDiagnosticSessionByStartParams) (FindDiagnosticSessionByStartRow, error) {
	row := q.db.QueryRow(ctx, findDiagnosticSessionByStart, arg.OwnerID, arg.StartRequestKey)
	var i FindDiagnosticSessionByStartRow
	err := row.Scan(&i.SessionData, &i.StartRequestDigest)
	return i, err
}

const getDiagnosticSession = `-- name: GetDiagnosticSession :one
SELECT session_data
FROM diagnostic_sessions
WHERE owner_id = $1::text
  AND id = $2::text
`

type GetDiagnosticSessionParams struct {
	OwnerID string
	ID      string
}

func (q *Queries) GetDiagnosticSession(ctx context.Context, arg GetDiagnosticSessionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDiagnosticSession, arg.OwnerID, arg.ID)
	var session_data []byte
	err := row.Scan(&session_data)
	return session_data, err
}
