// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	TokenHash []byte
	SessionID string
	ExpiresAt int64
}

type AldLevel struct {
	ID    string
	Code  string
	Label string
}

type AssignmentResponse struct {
	ID              string
	AssignmentID    string
	TranscriptionID *string
	AnswerText      string
	Score           *int16
	Feedback        []byte
	CreatedAt       int64
}

type AudioAsset struct {
	ID            string
	Instruction   string
	ObjectKey     string
	Status        string
	Bucket        *string
	StorageUri    *string
	AudioUrl      *string
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	LeaseUntil    pgtype.Timestamptz
	ClaimToken    *string
	LastErrorCode *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AuthSession struct {
	ID        string
	UserID    string
	ExpiresAt int64
	RevokedAt *int64
}

type Competency struct {
	ID       string
	Name     string
	Revision int64
}

type CompetencyMapImport struct {
	Revision              int64
	Singleton             bool
	ImportedAt            int64
	ImportedBy            string
	CompetencyCount       int32
	ConstituentCount      int32
	OutcomeCount          int32
	TaskCount             int32
	SourceFormat          string
	SourceHeaders         []byte
	UnparsedTaskCellCount int32
}

type CompetencyMapSourceRow struct {
	Revision   int64
	RowIndex   int32
	SourceLine int32
	Cells      []byte
}

type CompetencyMapState struct {
	Singleton bool
	Revision  int64
}

type Constituent struct {
	ID           string
	CompetencyID string
	Name         string
	TopicLevelID *string
}

type ConstituentCurriculumProfile struct {
	ConstituentID      string
	CurriculumSections string
}

type ConstituentSection struct {
	ID            string
	Revision      int64
	ConstituentID string
	SectionID     string
}

type ConstituentSectionCompetency struct {
	Revision               int64
	ConstituentSectionID   string
	CurriculumCompetencyID string
}

type CurriculumCompetency struct {
	ID       string
	Revision int64
	Code     string
}

type CurriculumSection struct {
	ID       string
	Revision int64
	Code     string
	Title    string
}

type GenerationRun struct {
	ID               string
	OutcomeID        string
	MapRevision      int64
	Model            string
	PromptVersion    string
	RequestKey       string
	RequestedProfile []byte
	CreatedAt        int64
}

type GenerationRunChunk struct {
	GenerationRunID string
	ChunkID         string
}

type GenerationRunExample struct {
	GenerationRunID string
	TaskID          string
}

type LearningSession struct {
	ID          string
	UserID      string
	MapRevision int64
	MapSnapshot []byte
	Status      string
	CreatedAt   int64
	CompletedAt *int64
}

type MaterialChunk struct {
	ID           string
	MaterialName string
	Ordinal      int32
	Content      string
	CreatedAt    int64
	SearchVector interface{}
}

type MaterialChunkOutcome struct {
	ChunkID   string
	OutcomeID string
}

type MaterialEmbedding struct {
	ChunkID     string
	Model       string
	Dimensions  int32
	MapRevision int64
	Embedding   []float64
}

type Outcome struct {
	ID                 string
	ConstituentID      string
	Name               string
	IncludeInTest      *bool
	TaxonomyID         *string
	AldLevelID         *string
	Importance         *int16
	EducationalContent *string
}

type OutcomeSourceRow struct {
	OutcomeID      string
	SourceRevision int64
	SourceRowIndex int32
}

type RefreshToken struct {
	TokenHash []byte
	SessionID string
	UsedAt    *int64
}

type Task struct {
	ID                string
	OutcomeID         string
	Question          string
	Criteria          *string
	SourceRow         *int32
	SourceColumn      *string
	Options           []byte
	VoiceInstruction  *string
	ReferenceAnswer   *string
	Origin            string
	GenerationRunID   *string
	SourceRevision    *int64
	SourceRowIndex    *int32
	SourceColumnIndex *int32
	CreatedAt         int64
	AudioAssetID      *string
}

type TaskAssignment struct {
	ID              string
	SessionID       string
	TaskID          *string
	Sequence        int32
	Role            string
	TaskSnapshot    []byte
	ProfileSnapshot []byte
	CreatedAt       int64
}

type Taxonomy struct {
	ID    string
	Code  string
	Label string
}

type TopicLevel struct {
	ID    string
	Code  string
	Label string
}

type Transcription struct {
	ID        string
	UserID    string
	Text      string
	CreatedAt int64
}

type User struct {
	ID           string
	Email        string
	DisplayName  *string
	PasswordHash string
	Role         string
	CreatedAt    int64
}

type Variant struct {
	ID                      string
	UserID                  string
	CreateRequestKey        string
	MapRevision             int64
	AlgorithmVersion        string
	IncludedCompetencyCount int32
	SkippedCompetencies     []byte
	CreatedAt               int64
}

type VariantTask struct {
	ID                   string
	VariantID            string
	LiveTaskID           *string
	SourceTaskIDSnapshot string
	CompetencyPosition   int32
	Slot                 int16
	Role                 string
	TaskSnapshot         []byte
	ProfileSnapshot      []byte
	AudioAssetID         *string
}
