// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subject.sql

package db

import (
	"context"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects(id, name, created_at)
VALUES ($1, $2, $3)
RETURNING id, name
`

type CreateSubjectParams struct {
	ID        string
	Name      string
	CreatedAt int64
}

type CreateSubjectRow struct {
	ID   string
	Name string
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (CreateSubjectRow, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.ID, arg.Name, arg.CreatedAt)
	var i CreateSubjectRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT subject.id, subject.name,
       EXISTS (
           SELECT 1
           FROM competencies competency
           JOIN constituents constituent ON constituent.competency_id = competency.id
           JOIN outcomes outcome ON outcome.constituent_id = constituent.id
           JOIN taxonomies taxonomy ON taxonomy.id = outcome.taxonomy_id
           JOIN tasks task ON task.outcome_id = outcome.id
           WHERE competency.revision = subject.active_revision
             AND outcome.include_in_test IS TRUE
             AND taxonomy.code IN ('knowledge', 'understanding', 'application', 'analysis')
             AND outcome.importance BETWEEN 1 AND 5
             AND task.origin IN ('authored', 'ai_generated')
             AND task.question ~ '[^[:space:]]'
             AND task.voice_instruction ~ '[^[:space:]]'
             AND task.reference_answer ~ '[^[:space:]]'
       ) AS ready
FROM subjects subject
ORDER BY lower(subject.name), subject.id
`

type ListSubjectsRow struct {
	ID    string
	Name  string
	Ready bool
}

func (q *Queries) ListSubjects(ctx context.Context) ([]ListSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubjectsRow{}
	for rows.Next() {
		var i ListSubjectsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Ready); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
