// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_audio.sql

package db

import (
	"context"
)

const cancelClaimedTaskAudio = `-- name: CancelClaimedTaskAudio :execrows
UPDATE audio_assets
SET status = 'cancelled', lease_until = NULL, claim_token = NULL,
    last_error_code = 'task_no_longer_current', updated_at = now()
WHERE audio_assets.id = $1 AND status = 'processing' AND claim_token = $2
  AND NOT EXISTS (
      SELECT 1
      FROM tasks task
      JOIN outcomes outcome ON outcome.id = task.outcome_id
      JOIN constituents constituent ON constituent.id = outcome.constituent_id
      JOIN competencies competency ON competency.id = constituent.competency_id
      JOIN subjects subject ON subject.active_revision = competency.revision
      WHERE task.audio_asset_id = audio_assets.id
  )
`

type CancelClaimedTaskAudioParams struct {
	ID         string
	ClaimToken *string
}

func (q *Queries) CancelClaimedTaskAudio(ctx context.Context, arg CancelClaimedTaskAudioParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelClaimedTaskAudio, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelPendingTaskAudioForSubject = `-- name: CancelPendingTaskAudioForSubject :execrows
UPDATE audio_assets asset
SET status = 'cancelled', last_error_code = 'task_no_longer_current', updated_at = now()
WHERE asset.status = 'pending'
  AND EXISTS (
      SELECT 1
      FROM tasks task
      JOIN outcomes outcome ON outcome.id = task.outcome_id
      JOIN constituents constituent ON constituent.id = outcome.constituent_id
      JOIN competencies competency ON competency.id = constituent.competency_id
      JOIN subjects subject ON subject.active_revision = competency.revision
      WHERE task.audio_asset_id = asset.id AND subject.id = $1
  )
`

func (q *Queries) CancelPendingTaskAudioForSubject(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, cancelPendingTaskAudioForSubject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimTaskAudio = `-- name: ClaimTaskAudio :one
WITH candidate AS (
    SELECT id FROM audio_assets
    WHERE status = 'pending' AND next_attempt_at <= now() AND attempts < 5
      AND EXISTS (
          SELECT 1
          FROM tasks task
          JOIN outcomes outcome ON outcome.id = task.outcome_id
          JOIN constituents constituent ON constituent.id = outcome.constituent_id
          JOIN competencies competency ON competency.id = constituent.competency_id
          JOIN subjects subject ON subject.active_revision = competency.revision
          WHERE task.audio_asset_id = audio_assets.id
      )
    ORDER BY created_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE audio_assets asset
SET status = 'processing',
    attempts = asset.attempts + 1,
    claim_token = $1,
    lease_until = now() + $2::double precision * interval '1 second',
    updated_at = now()
FROM candidate
WHERE asset.id = candidate.id
RETURNING asset.id, asset.instruction, asset.object_key, asset.bucket, asset.storage_uri,
          asset.audio_url, asset.status, asset.attempts
`

type ClaimTaskAudioParams struct {
	ClaimToken   *string
	LeaseSeconds float64
}

type ClaimTaskAudioRow struct {
	ID          string
	Instruction string
	ObjectKey   string
	Bucket      *string
	StorageUri  *string
	AudioUrl    *string
	Status      string
	Attempts    int32
}

func (q *Queries) ClaimTaskAudio(ctx context.Context, arg ClaimTaskAudioParams) (ClaimTaskAudioRow, error) {
	row := q.db.QueryRow(ctx, claimTaskAudio, arg.ClaimToken, arg.LeaseSeconds)
	var i ClaimTaskAudioRow
	err := row.Scan(
		&i.ID,
		&i.Instruction,
		&i.ObjectKey,
		&i.Bucket,
		&i.StorageUri,
		&i.AudioUrl,
		&i.Status,
		&i.Attempts,
	)
	return i, err
}

const claimTaskAudioForRepair = `-- name: ClaimTaskAudioForRepair :one
WITH candidate AS MATERIALIZED (
    SELECT asset.id, asset.bucket AS previous_bucket
    FROM audio_assets asset
    WHERE asset.id = $1
      AND asset.status IN ('ready', 'failed')
      AND EXISTS (
      SELECT 1
      FROM tasks task
      JOIN outcomes outcome ON outcome.id = task.outcome_id
      JOIN constituents constituent ON constituent.id = outcome.constituent_id
      JOIN competencies competency ON competency.id = constituent.competency_id
      JOIN subjects subject ON subject.active_revision = competency.revision
      WHERE task.audio_asset_id = asset.id
      )
    FOR UPDATE
), claimed AS (
    UPDATE audio_assets asset
    SET status = 'processing',
        attempts = 1,
        bucket = NULL,
        storage_uri = NULL,
        audio_url = NULL,
        claim_token = $2,
        lease_until = now() + $3::double precision * interval '1 second',
        updated_at = now()
    FROM candidate
    WHERE asset.id = candidate.id AND asset.status IN ('ready', 'failed')
    RETURNING asset.id, asset.instruction, asset.object_key, asset.bucket, asset.storage_uri,
              asset.audio_url, asset.status, asset.attempts, candidate.previous_bucket
)
SELECT id, instruction, object_key, bucket, storage_uri, audio_url, status, attempts, previous_bucket FROM claimed
`

type ClaimTaskAudioForRepairParams struct {
	ID           string
	ClaimToken   *string
	LeaseSeconds float64
}

type ClaimTaskAudioForRepairRow struct {
	ID             string
	Instruction    string
	ObjectKey      string
	Bucket         *string
	StorageUri     *string
	AudioUrl       *string
	Status         string
	Attempts       int32
	PreviousBucket *string
}

func (q *Queries) ClaimTaskAudioForRepair(ctx context.Context, arg ClaimTaskAudioForRepairParams) (ClaimTaskAudioForRepairRow, error) {
	row := q.db.QueryRow(ctx, claimTaskAudioForRepair, arg.ID, arg.ClaimToken, arg.LeaseSeconds)
	var i ClaimTaskAudioForRepairRow
	err := row.Scan(
		&i.ID,
		&i.Instruction,
		&i.ObjectKey,
		&i.Bucket,
		&i.StorageUri,
		&i.AudioUrl,
		&i.Status,
		&i.Attempts,
		&i.PreviousBucket,
	)
	return i, err
}

const completeTaskAudio = `-- name: CompleteTaskAudio :execrows
UPDATE audio_assets
SET status = 'ready', bucket = $3, storage_uri = $4, audio_url = $5,
    lease_until = NULL, claim_token = NULL, last_error_code = NULL, updated_at = now()
WHERE id = $1 AND status = 'processing' AND claim_token = $2
`

type CompleteTaskAudioParams struct {
	ID         string
	ClaimToken *string
	Bucket     *string
	StorageUri *string
	AudioUrl   *string
}

func (q *Queries) CompleteTaskAudio(ctx context.Context, arg CompleteTaskAudioParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeTaskAudio,
		arg.ID,
		arg.ClaimToken,
		arg.Bucket,
		arg.StorageUri,
		arg.AudioUrl,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueTaskAudio = `-- name: EnqueueTaskAudio :exec
INSERT INTO audio_assets(id, instruction, object_key)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type EnqueueTaskAudioParams struct {
	ID          string
	Instruction string
	ObjectKey   string
}

func (q *Queries) EnqueueTaskAudio(ctx context.Context, arg EnqueueTaskAudioParams) error {
	_, err := q.db.Exec(ctx, enqueueTaskAudio, arg.ID, arg.Instruction, arg.ObjectKey)
	return err
}

const failTaskAudio = `-- name: FailTaskAudio :execrows
UPDATE audio_assets
SET status = CASE
        WHEN NOT EXISTS (
            SELECT 1
            FROM tasks task
            JOIN outcomes outcome ON outcome.id = task.outcome_id
            JOIN constituents constituent ON constituent.id = outcome.constituent_id
            JOIN competencies competency ON competency.id = constituent.competency_id
            JOIN subjects subject ON subject.active_revision = competency.revision
            WHERE task.audio_asset_id = audio_assets.id
        ) THEN 'cancelled'
        WHEN attempts >= 5 THEN 'failed'
        ELSE 'pending'
    END,
    next_attempt_at = CASE
        WHEN attempts >= 5 OR NOT EXISTS (
            SELECT 1
            FROM tasks task
            JOIN outcomes outcome ON outcome.id = task.outcome_id
            JOIN constituents constituent ON constituent.id = outcome.constituent_id
            JOIN competencies competency ON competency.id = constituent.competency_id
            JOIN subjects subject ON subject.active_revision = competency.revision
            WHERE task.audio_asset_id = audio_assets.id
        ) THEN next_attempt_at
        ELSE now() + $1::double precision * interval '1 second'
    END,
    lease_until = NULL, claim_token = NULL,
    last_error_code = CASE
        WHEN NOT EXISTS (
            SELECT 1
            FROM tasks task
            JOIN outcomes outcome ON outcome.id = task.outcome_id
            JOIN constituents constituent ON constituent.id = outcome.constituent_id
            JOIN competencies competency ON competency.id = constituent.competency_id
            JOIN subjects subject ON subject.active_revision = competency.revision
            WHERE task.audio_asset_id = audio_assets.id
        ) THEN 'task_no_longer_current'
        ELSE $2
    END,
    updated_at = now()
WHERE audio_assets.id = $3 AND status = 'processing' AND claim_token = $4
`

type FailTaskAudioParams struct {
	DelaySeconds float64
	ErrorCode    *string
	ID           string
	ClaimToken   *string
}

func (q *Queries) FailTaskAudio(ctx context.Context, arg FailTaskAudioParams) (int64, error) {
	result, err := q.db.Exec(ctx, failTaskAudio,
		arg.DelaySeconds,
		arg.ErrorCode,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findReadyTaskAudioByInstruction = `-- name: FindReadyTaskAudioByInstruction :one
SELECT id, instruction, object_key, bucket, storage_uri, audio_url, status, attempts
FROM audio_assets
WHERE instruction = $1 AND id <> $2 AND status = 'ready'
ORDER BY updated_at DESC, id
LIMIT 1
`

type FindReadyTaskAudioByInstructionParams struct {
	Instruction string
	ID          string
}

type FindReadyTaskAudioByInstructionRow struct {
	ID          string
	Instruction string
	ObjectKey   string
	Bucket      *string
	StorageUri  *string
	AudioUrl    *string
	Status      string
	Attempts    int32
}

// A ready recording of the same instruction can be copied instead of synthesized.
func (q *Queries) FindReadyTaskAudioByInstruction(ctx context.Context, arg FindReadyTaskAudioByInstructionParams) (FindReadyTaskAudioByInstructionRow, error) {
	row := q.db.QueryRow(ctx, findReadyTaskAudioByInstruction, arg.Instruction, arg.ID)
	var i FindReadyTaskAudioByInstructionRow
	err := row.Scan(
		&i.ID,
		&i.Instruction,
		&i.ObjectKey,
		&i.Bucket,
		&i.StorageUri,
		&i.AudioUrl,
		&i.Status,
		&i.Attempts,
	)
	return i, err
}

const getAccessibleTaskAudio = `-- name: GetAccessibleTaskAudio :one
SELECT asset.id, asset.instruction, asset.object_key, asset.bucket, asset.storage_uri,
       asset.audio_url, asset.status, asset.attempts
FROM audio_assets asset
WHERE asset.id = $2 AND (
    EXISTS (SELECT 1 FROM tasks task WHERE task.audio_asset_id = asset.id)
    OR EXISTS (
        SELECT 1 FROM variant_tasks variant_task
        JOIN variants variant ON variant.id = variant_task.variant_id
        WHERE variant.user_id = $1 AND variant_task.audio_asset_id = asset.id
    )
    OR EXISTS (
        SELECT 1 FROM training_exercises exercise
        JOIN training_sessions session ON session.id=exercise.session_id
        WHERE session.owner_id=$1 AND exercise.audio_asset_id=asset.id
          AND session.state_data->'Current'->>'ID'=exercise.id
    )
)
`

type GetAccessibleTaskAudioParams struct {
	UserID string
	ID     string
}

type GetAccessibleTaskAudioRow struct {
	ID          string
	Instruction string
	ObjectKey   string
	Bucket      *string
	StorageUri  *string
	AudioUrl    *string
	Status      string
	Attempts    int32
}

func (q *Queries) GetAccessibleTaskAudio(ctx context.Context, arg GetAccessibleTaskAudioParams) (GetAccessibleTaskAudioRow, error) {
	row := q.db.QueryRow(ctx, getAccessibleTaskAudio, arg.UserID, arg.ID)
	var i GetAccessibleTaskAudioRow
	err := row.Scan(
		&i.ID,
		&i.Instruction,
		&i.ObjectKey,
		&i.Bucket,
		&i.StorageUri,
		&i.AudioUrl,
		&i.Status,
		&i.Attempts,
	)
	return i, err
}

const getTaskAudio = `-- name: GetTaskAudio :one
SELECT id, instruction, object_key, bucket, storage_uri, audio_url, status, attempts
FROM audio_assets WHERE id = $1
`

type GetTaskAudioRow struct {
	ID          string
	Instruction string
	ObjectKey   string
	Bucket      *string
	StorageUri  *string
	AudioUrl    *string
	Status      string
	Attempts    int32
}

func (q *Queries) GetTaskAudio(ctx context.Context, id string) (GetTaskAudioRow, error) {
	row := q.db.QueryRow(ctx, getTaskAudio, id)
	var i GetTaskAudioRow
	err := row.Scan(
		&i.ID,
		&i.Instruction,
		&i.ObjectKey,
		&i.Bucket,
		&i.StorageUri,
		&i.AudioUrl,
		&i.Status,
		&i.Attempts,
	)
	return i, err
}

const insertTaskAudioAsset = `-- name: InsertTaskAudioAsset :one
INSERT INTO audio_assets(id, instruction, object_key)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET instruction = audio_assets.instruction
RETURNING instruction
`

type InsertTaskAudioAssetParams struct {
	ID          string
	Instruction string
	ObjectKey   string
}

func (q *Queries) InsertTaskAudioAsset(ctx context.Context, arg InsertTaskAudioAssetParams) (string, error) {
	row := q.db.QueryRow(ctx, insertTaskAudioAsset, arg.ID, arg.Instruction, arg.ObjectKey)
	var instruction string
	err := row.Scan(&instruction)
	return instruction, err
}

const isCurrentTaskAudio = `-- name: IsCurrentTaskAudio :one
SELECT EXISTS (
    SELECT 1
    FROM audio_assets asset
    JOIN tasks task ON task.audio_asset_id = asset.id
    JOIN outcomes outcome ON outcome.id = task.outcome_id
    JOIN constituents constituent ON constituent.id = outcome.constituent_id
    JOIN competencies competency ON competency.id = constituent.competency_id
    JOIN subjects subject ON subject.active_revision = competency.revision
    WHERE asset.id = $1
      AND asset.status = 'processing'
      AND asset.claim_token = $2
      AND asset.lease_until > now()
)
`

type IsCurrentTaskAudioParams struct {
	ID         string
	ClaimToken *string
}

func (q *Queries) IsCurrentTaskAudio(ctx context.Context, arg IsCurrentTaskAudioParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCurrentTaskAudio, arg.ID, arg.ClaimToken)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const linkTaskAudioAsset = `-- name: LinkTaskAudioAsset :execrows
UPDATE tasks SET audio_asset_id = $2 WHERE id = $1
`

type LinkTaskAudioAssetParams struct {
	ID           string
	AudioAssetID *string
}

func (q *Queries) LinkTaskAudioAsset(ctx context.Context, arg LinkTaskAudioAssetParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkTaskAudioAsset, arg.ID, arg.AudioAssetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recoverExpiredTaskAudio = `-- name: RecoverExpiredTaskAudio :exec
UPDATE audio_assets
SET status = CASE
        WHEN NOT EXISTS (
            SELECT 1
            FROM tasks task
            JOIN outcomes outcome ON outcome.id = task.outcome_id
            JOIN constituents constituent ON constituent.id = outcome.constituent_id
            JOIN competencies competency ON competency.id = constituent.competency_id
            JOIN subjects subject ON subject.active_revision = competency.revision
            WHERE task.audio_asset_id = audio_assets.id
        ) THEN 'cancelled'
        WHEN attempts >= 5 THEN 'failed'
        ELSE 'pending'
    END,
    lease_until = NULL,
    claim_token = NULL,
    next_attempt_at = CASE WHEN attempts >= 5 THEN next_attempt_at ELSE now() END,
    last_error_code = CASE
        WHEN NOT EXISTS (
            SELECT 1
            FROM tasks task
            JOIN outcomes outcome ON outcome.id = task.outcome_id
            JOIN constituents constituent ON constituent.id = outcome.constituent_id
            JOIN competencies competency ON competency.id = constituent.competency_id
            JOIN subjects subject ON subject.active_revision = competency.revision
            WHERE task.audio_asset_id = audio_assets.id
        ) THEN 'task_no_longer_current'
        WHEN attempts >= 5 THEN 'attempts_exhausted'
        ELSE last_error_code
    END,
    updated_at = now()
WHERE status = 'processing' AND lease_until <= now()
`

func (q *Queries) RecoverExpiredTaskAudio(ctx context.Context) error {
	_, err := q.db.Exec(ctx, recoverExpiredTaskAudio)
	return err
}
