// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training.sql

package db

import (
	"context"
)

const findTrainingAnswer = `-- name: FindTrainingAnswer :one
SELECT fingerprint,response_data FROM training_attempts WHERE session_id=$1 AND request_key=$2
`

type FindTrainingAnswerParams struct {
	SessionID  string
	RequestKey string
}

type FindTrainingAnswerRow struct {
	Fingerprint  string
	ResponseData []byte
}

func (q *Queries) FindTrainingAnswer(ctx context.Context, arg FindTrainingAnswerParams) (FindTrainingAnswerRow, error) {
	row := q.db.QueryRow(ctx, findTrainingAnswer, arg.SessionID, arg.RequestKey)
	var i FindTrainingAnswerRow
	err := row.Scan(&i.Fingerprint, &i.ResponseData)
	return i, err
}

const findTrainingByDiagnostic = `-- name: FindTrainingByDiagnostic :one
SELECT state_data FROM training_sessions WHERE owner_id=$1 AND diagnostic_id=$2
`

type FindTrainingByDiagnosticParams struct {
	OwnerID      string
	DiagnosticID string
}

func (q *Queries) FindTrainingByDiagnostic(ctx context.Context, arg FindTrainingByDiagnosticParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, findTrainingByDiagnostic, arg.OwnerID, arg.DiagnosticID)
	var state_data []byte
	err := row.Scan(&state_data)
	return state_data, err
}

const findTrainingStartKey = `-- name: FindTrainingStartKey :one
SELECT diagnostic_id,session_id FROM training_start_requests WHERE owner_id=$1 AND request_key=$2
`

type FindTrainingStartKeyParams struct {
	OwnerID    string
	RequestKey string
}

type FindTrainingStartKeyRow struct {
	DiagnosticID string
	SessionID    string
}

func (q *Queries) FindTrainingStartKey(ctx context.Context, arg FindTrainingStartKeyParams) (FindTrainingStartKeyRow, error) {
	row := q.db.QueryRow(ctx, findTrainingStartKey, arg.OwnerID, arg.RequestKey)
	var i FindTrainingStartKeyRow
	err := row.Scan(&i.DiagnosticID, &i.SessionID)
	return i, err
}

const insertTrainingAttempt = `-- name: InsertTrainingAttempt :exec
INSERT INTO training_attempts(session_id,sequence,request_key,fingerprint,exercise_id,attempt_data,response_data) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type InsertTrainingAttemptParams struct {
	SessionID    string
	Sequence     int64
	RequestKey   string
	Fingerprint  string
	ExerciseID   string
	AttemptData  []byte
	ResponseData []byte
}

func (q *Queries) InsertTrainingAttempt(ctx context.Context, arg InsertTrainingAttemptParams) error {
	_, err := q.db.Exec(ctx, insertTrainingAttempt,
		arg.SessionID,
		arg.Sequence,
		arg.RequestKey,
		arg.Fingerprint,
		arg.ExerciseID,
		arg.AttemptData,
		arg.ResponseData,
	)
	return err
}

const insertTrainingExercise = `-- name: InsertTrainingExercise :exec
INSERT INTO training_exercises(id,session_id,round,target_index,exercise_data,audio_asset_id) VALUES($1,$2,$3,$4,$5,$6)
`

type InsertTrainingExerciseParams struct {
	ID           string
	SessionID    string
	Round        int64
	TargetIndex  int32
	ExerciseData []byte
	AudioAssetID *string
}

func (q *Queries) InsertTrainingExercise(ctx context.Context, arg InsertTrainingExerciseParams) error {
	_, err := q.db.Exec(ctx, insertTrainingExercise,
		arg.ID,
		arg.SessionID,
		arg.Round,
		arg.TargetIndex,
		arg.ExerciseData,
		arg.AudioAssetID,
	)
	return err
}

const insertTrainingSession = `-- name: InsertTrainingSession :exec
INSERT INTO training_sessions(id,owner_id,diagnostic_id,subject_id,state_data) VALUES($1,$2,$3,$4,$5)
`

type InsertTrainingSessionParams struct {
	ID           string
	OwnerID      string
	DiagnosticID string
	SubjectID    string
	StateData    []byte
}

func (q *Queries) InsertTrainingSession(ctx context.Context, arg InsertTrainingSessionParams) error {
	_, err := q.db.Exec(ctx, insertTrainingSession,
		arg.ID,
		arg.OwnerID,
		arg.DiagnosticID,
		arg.SubjectID,
		arg.StateData,
	)
	return err
}

const insertTrainingStartKey = `-- name: InsertTrainingStartKey :exec
INSERT INTO training_start_requests(owner_id,request_key,diagnostic_id,session_id) VALUES($1,$2,$3,$4)
`

type InsertTrainingStartKeyParams struct {
	OwnerID      string
	RequestKey   string
	DiagnosticID string
	SessionID    string
}

func (q *Queries) InsertTrainingStartKey(ctx context.Context, arg InsertTrainingStartKeyParams) error {
	_, err := q.db.Exec(ctx, insertTrainingStartKey,
		arg.OwnerID,
		arg.RequestKey,
		arg.DiagnosticID,
		arg.SessionID,
	)
	return err
}

const insertTrainingTarget = `-- name: InsertTrainingTarget :exec
INSERT INTO training_targets(session_id,position,target_data) VALUES($1,$2,$3)
`

type InsertTrainingTargetParams struct {
	SessionID  string
	Position   int32
	TargetData []byte
}

func (q *Queries) InsertTrainingTarget(ctx context.Context, arg InsertTrainingTargetParams) error {
	_, err := q.db.Exec(ctx, insertTrainingTarget, arg.SessionID, arg.Position, arg.TargetData)
	return err
}

const lockTrainingDiagnostic = `-- name: LockTrainingDiagnostic :one
SELECT status FROM diagnostic_sessions WHERE owner_id=$1 AND id=$2 FOR UPDATE
`

type LockTrainingDiagnosticParams struct {
	OwnerID string
	ID      string
}

func (q *Queries) LockTrainingDiagnostic(ctx context.Context, arg LockTrainingDiagnosticParams) (string, error) {
	row := q.db.QueryRow(ctx, lockTrainingDiagnostic, arg.OwnerID, arg.ID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const lockTrainingOwner = `-- name: LockTrainingOwner :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 901))
`

func (q *Queries) LockTrainingOwner(ctx context.Context, ownerID string) error {
	_, err := q.db.Exec(ctx, lockTrainingOwner, ownerID)
	return err
}

const lockTrainingSession = `-- name: LockTrainingSession :one
SELECT state_data,reservation_data,COALESCE(lease_until>now(),false)::boolean AS leased
FROM training_sessions WHERE owner_id=$1 AND id=$2 FOR UPDATE
`

type LockTrainingSessionParams struct {
	OwnerID string
	ID      string
}

type LockTrainingSessionRow struct {
	StateData       []byte
	ReservationData []byte
	Leased          bool
}

func (q *Queries) LockTrainingSession(ctx context.Context, arg LockTrainingSessionParams) (LockTrainingSessionRow, error) {
	row := q.db.QueryRow(ctx, lockTrainingSession, arg.OwnerID, arg.ID)
	var i LockTrainingSessionRow
	err := row.Scan(&i.StateData, &i.ReservationData, &i.Leased)
	return i, err
}

const readTrainingHistory = `-- name: ReadTrainingHistory :many
SELECT attempt_data,sequence FROM training_attempts WHERE session_id=$1 AND sequence<$2::bigint ORDER BY sequence DESC LIMIT $3::integer
`

type ReadTrainingHistoryParams struct {
	SessionID      string
	BeforeSequence int64
	PageSize       int32
}

type ReadTrainingHistoryRow struct {
	AttemptData []byte
	Sequence    int64
}

func (q *Queries) ReadTrainingHistory(ctx context.Context, arg ReadTrainingHistoryParams) ([]ReadTrainingHistoryRow, error) {
	rows, err := q.db.Query(ctx, readTrainingHistory, arg.SessionID, arg.BeforeSequence, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadTrainingHistoryRow{}
	for rows.Next() {
		var i ReadTrainingHistoryRow
		if err := rows.Scan(&i.AttemptData, &i.Sequence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readTrainingSession = `-- name: ReadTrainingSession :one
SELECT state_data FROM training_sessions WHERE owner_id=$1 AND id=$2
`

type ReadTrainingSessionParams struct {
	OwnerID string
	ID      string
}

func (q *Queries) ReadTrainingSession(ctx context.Context, arg ReadTrainingSessionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, readTrainingSession, arg.OwnerID, arg.ID)
	var state_data []byte
	err := row.Scan(&state_data)
	return state_data, err
}

const saveTrainingReservation = `-- name: SaveTrainingReservation :exec
UPDATE training_sessions SET reservation_data=$3,lease_until=CASE WHEN $4::boolean THEN now()+interval '5 minutes' ELSE NULL END WHERE owner_id=$1 AND id=$2
`

type SaveTrainingReservationParams struct {
	OwnerID         string
	ID              string
	ReservationData []byte
	Leased          bool
}

func (q *Queries) SaveTrainingReservation(ctx context.Context, arg SaveTrainingReservationParams) error {
	_, err := q.db.Exec(ctx, saveTrainingReservation,
		arg.OwnerID,
		arg.ID,
		arg.ReservationData,
		arg.Leased,
	)
	return err
}

const saveTrainingState = `-- name: SaveTrainingState :exec
UPDATE training_sessions SET state_data=$3,reservation_data=NULL,lease_until=NULL WHERE owner_id=$1 AND id=$2
`

type SaveTrainingStateParams struct {
	OwnerID   string
	ID        string
	StateData []byte
}

func (q *Queries) SaveTrainingState(ctx context.Context, arg SaveTrainingStateParams) error {
	_, err := q.db.Exec(ctx, saveTrainingState, arg.OwnerID, arg.ID, arg.StateData)
	return err
}
