// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: variants.sql

package db

import (
	"context"
)

const findSubjectForVariantList = `-- name: FindSubjectForVariantList :one
SELECT id FROM subjects WHERE id = $1
`

func (q *Queries) FindSubjectForVariantList(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, findSubjectForVariantList, id)
	err := row.Scan(&id)
	return id, err
}

const findVariantByRequestKey = `-- name: FindVariantByRequestKey :one
SELECT id, subject_id FROM variants WHERE user_id = $1 AND create_request_key = $2
`

type FindVariantByRequestKeyParams struct {
	UserID           string
	CreateRequestKey string
}

type FindVariantByRequestKeyRow struct {
	ID        string
	SubjectID string
}

func (q *Queries) FindVariantByRequestKey(ctx context.Context, arg FindVariantByRequestKeyParams) (FindVariantByRequestKeyRow, error) {
	row := q.db.QueryRow(ctx, findVariantByRequestKey, arg.UserID, arg.CreateRequestKey)
	var i FindVariantByRequestKeyRow
	err := row.Scan(&i.ID, &i.SubjectID)
	return i, err
}

const insertVariant = `-- name: InsertVariant :one
INSERT INTO variants(id, user_id, create_request_key, map_revision, algorithm_version,
                     included_competency_count, skipped_competencies, created_at, subject_id, subject_name_snapshot)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (user_id, create_request_key) DO NOTHING
RETURNING id
`

type InsertVariantParams struct {
	ID                      string
	UserID                  string
	CreateRequestKey        string
	MapRevision             int64
	AlgorithmVersion        string
	IncludedCompetencyCount int32
	SkippedCompetencies     []byte
	CreatedAt               int64
	SubjectID               string
	SubjectNameSnapshot     string
}

func (q *Queries) InsertVariant(ctx context.Context, arg InsertVariantParams) (string, error) {
	row := q.db.QueryRow(ctx, insertVariant,
		arg.ID,
		arg.UserID,
		arg.CreateRequestKey,
		arg.MapRevision,
		arg.AlgorithmVersion,
		arg.IncludedCompetencyCount,
		arg.SkippedCompetencies,
		arg.CreatedAt,
		arg.SubjectID,
		arg.SubjectNameSnapshot,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertVariantTask = `-- name: InsertVariantTask :exec
INSERT INTO variant_tasks(id, variant_id, live_task_id, source_task_id_snapshot, audio_asset_id,
                          competency_position, slot, role, task_snapshot, profile_snapshot)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertVariantTaskParams struct {
	ID                   string
	VariantID            string
	LiveTaskID           *string
	SourceTaskIDSnapshot string
	AudioAssetID         *string
	CompetencyPosition   int32
	Slot                 int16
	Role                 string
	TaskSnapshot         []byte
	ProfileSnapshot      []byte
}

func (q *Queries) InsertVariantTask(ctx context.Context, arg InsertVariantTaskParams) error {
	_, err := q.db.Exec(ctx, insertVariantTask,
		arg.ID,
		arg.VariantID,
		arg.LiveTaskID,
		arg.SourceTaskIDSnapshot,
		arg.AudioAssetID,
		arg.CompetencyPosition,
		arg.Slot,
		arg.Role,
		arg.TaskSnapshot,
		arg.ProfileSnapshot,
	)
	return err
}

const listVariantsByOwner = `-- name: ListVariantsByOwner :many
SELECT id, map_revision, algorithm_version, included_competency_count,
       skipped_competencies, created_at, subject_id, subject_name_snapshot,
       (SELECT count(*) FROM variant_tasks vt WHERE vt.variant_id = variants.id) AS task_count
FROM variants
WHERE user_id = $1 AND subject_id = $2
  AND ($3::bigint IS NULL
       OR (created_at, id) < ($3::bigint, $4::text))
ORDER BY created_at DESC, id DESC
LIMIT $5::integer
`

type ListVariantsByOwnerParams struct {
	UserID          string
	SubjectID       string
	CursorCreatedAt *int64
	CursorID        *string
	PageSize        int32
}

type ListVariantsByOwnerRow struct {
	ID                      string
	MapRevision             int64
	AlgorithmVersion        string
	IncludedCompetencyCount int32
	SkippedCompetencies     []byte
	CreatedAt               int64
	SubjectID               string
	SubjectNameSnapshot     string
	TaskCount               int64
}

func (q *Queries) ListVariantsByOwner(ctx context.Context, arg ListVariantsByOwnerParams) ([]ListVariantsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listVariantsByOwner,
		arg.UserID,
		arg.SubjectID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantsByOwnerRow{}
	for rows.Next() {
		var i ListVariantsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.MapRevision,
			&i.AlgorithmVersion,
			&i.IncludedCompetencyCount,
			&i.SkippedCompetencies,
			&i.CreatedAt,
			&i.SubjectID,
			&i.SubjectNameSnapshot,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSubjectForVariant = `-- name: LockSubjectForVariant :one
SELECT id, name, COALESCE(active_revision, 0)::bigint AS active_revision
FROM subjects WHERE id = $1 FOR SHARE
`

type LockSubjectForVariantRow struct {
	ID             string
	Name           string
	ActiveRevision int64
}

func (q *Queries) LockSubjectForVariant(ctx context.Context, id string) (LockSubjectForVariantRow, error) {
	row := q.db.QueryRow(ctx, lockSubjectForVariant, id)
	var i LockSubjectForVariantRow
	err := row.Scan(&i.ID, &i.Name, &i.ActiveRevision)
	return i, err
}

const readVariantCandidates = `-- name: ReadVariantCandidates :many
SELECT $1::bigint AS revision,
       COALESCE((SELECT min(osr.source_row_index) FROM outcomes co
                 LEFT JOIN outcome_source_rows osr ON osr.outcome_id = co.id
                 WHERE co.constituent_id IN (
                     SELECT c2.id FROM constituents c2 WHERE c2.competency_id = competency.id
                 )), 2147483647)::bigint AS competency_source_order,
       COALESCE((SELECT min(source_row_index) FROM outcome_source_rows WHERE outcome_id = outcome.id), 2147483647)::bigint AS outcome_source_order,
       task.id AS task_id,
       jsonb_build_object(
           'id', task.id, 'question', task.question, 'options', task.options,
           'voice_instruction', task.voice_instruction, 'audio_asset_id', task.audio_asset_id,
           'reference_answer', task.reference_answer,
           'criteria', task.criteria, 'origin', task.origin, 'created_at', task.created_at,
           'source_row_index', task.source_row_index, 'source_column_index', task.source_column_index,
           'competency', jsonb_build_object('id', competency.id, 'name', competency.name),
           'constituent', jsonb_build_object(
               'id', constituent.id, 'name', constituent.name, 'topic_level_code', topic.code,
               'sections', COALESCE((SELECT jsonb_agg(jsonb_build_object(
                   'code', section.code, 'title', section.title,
                   'curriculum_competencies', COALESCE((SELECT jsonb_agg(curriculum.code ORDER BY curriculum.code)
                       FROM constituent_section_competencies mapped
                       JOIN curriculum_competencies curriculum ON curriculum.id = mapped.curriculum_competency_id
                       WHERE mapped.constituent_section_id = link.id), '[]'::jsonb)
               ) ORDER BY section.code)
               FROM constituent_sections link JOIN curriculum_sections section ON section.id = link.section_id
               WHERE link.constituent_id = constituent.id), '[]'::jsonb)
           ),
           'outcome', jsonb_build_object(
               'id', outcome.id, 'name', outcome.name, 'include_in_test', outcome.include_in_test,
               'taxonomy_code', taxonomy.code, 'ald_level_code', ald.code,
               'importance', outcome.importance, 'educational_content', outcome.educational_content
           )
       ) AS profile_json
FROM competencies competency
LEFT JOIN constituents constituent ON constituent.competency_id = competency.id
LEFT JOIN topic_levels topic ON topic.id = constituent.topic_level_id
LEFT JOIN outcomes outcome ON outcome.constituent_id = constituent.id
LEFT JOIN taxonomies taxonomy ON taxonomy.id = outcome.taxonomy_id
LEFT JOIN ald_levels ald ON ald.id = outcome.ald_level_id
LEFT JOIN tasks task ON task.outcome_id = outcome.id
WHERE competency.revision = $1::bigint
ORDER BY competency_source_order, competency.name, competency.id,
         outcome_source_order, outcome.name, outcome.id,
         CASE WHEN task.source_row_index IS NULL THEN 1 ELSE 0 END,
         task.source_row_index, task.source_column_index, task.created_at, task.id
`

type ReadVariantCandidatesRow struct {
	Revision              int64
	CompetencySourceOrder int64
	OutcomeSourceOrder    int64
	TaskID                *string
	ProfileJson           []byte
}

func (q *Queries) ReadVariantCandidates(ctx context.Context, revision int64) ([]ReadVariantCandidatesRow, error) {
	rows, err := q.db.Query(ctx, readVariantCandidates, revision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadVariantCandidatesRow{}
	for rows.Next() {
		var i ReadVariantCandidatesRow
		if err := rows.Scan(
			&i.Revision,
			&i.CompetencySourceOrder,
			&i.OutcomeSourceOrder,
			&i.TaskID,
			&i.ProfileJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readVariantHeaderByOwner = `-- name: ReadVariantHeaderByOwner :one
SELECT id, user_id, map_revision, algorithm_version, included_competency_count,
       skipped_competencies, created_at, subject_id, subject_name_snapshot
FROM variants WHERE id = $1 AND user_id = $2
`

type ReadVariantHeaderByOwnerParams struct {
	ID     string
	UserID string
}

type ReadVariantHeaderByOwnerRow struct {
	ID                      string
	UserID                  string
	MapRevision             int64
	AlgorithmVersion        string
	IncludedCompetencyCount int32
	SkippedCompetencies     []byte
	CreatedAt               int64
	SubjectID               string
	SubjectNameSnapshot     string
}

func (q *Queries) ReadVariantHeaderByOwner(ctx context.Context, arg ReadVariantHeaderByOwnerParams) (ReadVariantHeaderByOwnerRow, error) {
	row := q.db.QueryRow(ctx, readVariantHeaderByOwner, arg.ID, arg.UserID)
	var i ReadVariantHeaderByOwnerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MapRevision,
		&i.AlgorithmVersion,
		&i.IncludedCompetencyCount,
		&i.SkippedCompetencies,
		&i.CreatedAt,
		&i.SubjectID,
		&i.SubjectNameSnapshot,
	)
	return i, err
}

const readVariantTaskByOwner = `-- name: ReadVariantTaskByOwner :one
SELECT vt.id, vt.role, vt.audio_asset_id, vt.task_snapshot, vt.profile_snapshot
FROM variant_tasks vt JOIN variants v ON v.id = vt.variant_id
WHERE v.user_id = $1 AND v.id = $2 AND vt.id = $3
`

type ReadVariantTaskByOwnerParams struct {
	UserID string
	ID     string
	ID_2   string
}

type ReadVariantTaskByOwnerRow struct {
	ID              string
	Role            string
	AudioAssetID    *string
	TaskSnapshot    []byte
	ProfileSnapshot []byte
}

func (q *Queries) ReadVariantTaskByOwner(ctx context.Context, arg ReadVariantTaskByOwnerParams) (ReadVariantTaskByOwnerRow, error) {
	row := q.db.QueryRow(ctx, readVariantTaskByOwner, arg.UserID, arg.ID, arg.ID_2)
	var i ReadVariantTaskByOwnerRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.AudioAssetID,
		&i.TaskSnapshot,
		&i.ProfileSnapshot,
	)
	return i, err
}

const readVariantTasks = `-- name: ReadVariantTasks :many
SELECT id, competency_position, slot, role, source_task_id_snapshot, audio_asset_id, task_snapshot, profile_snapshot
FROM variant_tasks WHERE variant_id = $1 ORDER BY competency_position, slot
`

type ReadVariantTasksRow struct {
	ID                   string
	CompetencyPosition   int32
	Slot                 int16
	Role                 string
	SourceTaskIDSnapshot string
	AudioAssetID         *string
	TaskSnapshot         []byte
	ProfileSnapshot      []byte
}

func (q *Queries) ReadVariantTasks(ctx context.Context, variantID string) ([]ReadVariantTasksRow, error) {
	rows, err := q.db.Query(ctx, readVariantTasks, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadVariantTasksRow{}
	for rows.Next() {
		var i ReadVariantTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.CompetencyPosition,
			&i.Slot,
			&i.Role,
			&i.SourceTaskIDSnapshot,
			&i.AudioAssetID,
			&i.TaskSnapshot,
			&i.ProfileSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
