// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice.sql

package db

import (
	"context"
)

const getTranscriptionByOwner = `-- name: GetTranscriptionByOwner :one
SELECT text FROM transcriptions WHERE id = $1 AND user_id = $2
`

type GetTranscriptionByOwnerParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetTranscriptionByOwner(ctx context.Context, arg GetTranscriptionByOwnerParams) (string, error) {
	row := q.db.QueryRow(ctx, getTranscriptionByOwner, arg.ID, arg.UserID)
	var text string
	err := row.Scan(&text)
	return text, err
}

const insertTranscription = `-- name: InsertTranscription :exec
INSERT INTO transcriptions(id, user_id, text, created_at) VALUES ($1, $2, $3, $4)
`

type InsertTranscriptionParams struct {
	ID        string
	UserID    string
	Text      string
	CreatedAt int64
}

func (q *Queries) InsertTranscription(ctx context.Context, arg InsertTranscriptionParams) error {
	_, err := q.db.Exec(ctx, insertTranscription,
		arg.ID,
		arg.UserID,
		arg.Text,
		arg.CreatedAt,
	)
	return err
}
